[build]
  builder = "NIXPACKS"

[deploy]
  healthcheckPath = "/api/health"
  startCommand = "npm run start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  RAILPACK_NODE_VERSION = "20"